services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    volumes:
        - webring_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=quarkus
      - POSTGRESQL_PASSWORD=quarkus
      - POSTGRESQL_DATABASE=quarkus

volumes:
  webring_data:
    driver: local
