name: Build and Push Docker Images

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            qemu_arch: x86_64
            tag_suffix: ''
            latest_tag: latest
          - arch: arm64
            qemu_arch: aarch64
            tag_suffix: '-arm64'
            latest_tag: latest-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/${{ matrix.arch }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/app:${{ github.sha }}${{ matrix.tag_suffix }}
            ghcr.io/${{ github.repository_owner }}/app:${{ matrix.latest_tag }}
          push: true

      - name: Logout of GitHub Container Registry
        run: docker logout ghcr.io
